id: I1444B8EE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T05:02:51+00:00'
last_modified: '2022-06-07T18:08:32.621943+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1017177
  title: ཀུན་བྱེད་རྒྱལ་པོའི་འགྲེལ་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    EF89:
      image_group_id: I00EGS1017179
      title: ''
      total_pages: 512
      order: 1
      base_file: EF89.txt
    29A4:
      image_group_id: I00EGS1017180
      title: ''
      total_pages: 514
      order: 2
      base_file: 29A4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
